stages:
  - deploy

.deploy_application:
  stage: deploy
  before_script:
    - touch .env
    - |
      echo "ENV=${ENV}" >> .env
      echo "PROJECT_ID=${PROJECT_ID}" >> .env
      echo "APP_PORT=${APP_PORT}" >> .env
      echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
      echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
      echo "POSTGRES_DB=${POSTGRES_DB}" >> .env
      echo "POSTGRES_DATADIR=${POSTGRES_DATADIR}" >> .env
      echo "POSTGRES_PORT=${POSTGRES_PORT}" >> .env
      echo "ALLOWED_HOSTS=${ALLOWED_HOSTS}" >> .env
      echo "CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}" >> .env
      echo "DEBUG=${DEBUG}" >> .env
      echo "DJANGO_EMAIL_BACKEND=${DJANGO_EMAIL_BACKEND}" >> .env
      echo "DJANGO_DEFAULT_FROM_EMAIL=${DJANGO_DEFAULT_FROM_EMAIL}" >> .env
      echo "MAP_STYLE=${MAP_STYLE}" >> .env
      echo "MAP_ASSETS_BASE_URL=${MAP_ASSETS_BASE_URL}" >> .env
      echo "HERE_API_KEY=${HERE_API_KEY}" >> .env
      echo "VIRTUAL_HOST=${VIRTUAL_HOST}" >> .env
      echo "VIRTUAL_PORT=${VIRTUAL_PORT}" >> .env
      echo "LETSENCRYPT_HOST=${LETSENCRYPT_HOST}" >> .env
      echo "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}" >> .env
      echo "SECRET_KEY=${SECRET_KEY}" >> .env
      echo "DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST}" >> .env
      echo "EMAIL_PORT=${EMAIL_PORT}" >> .env
      echo "EMAIL_HOST_USER=${EMAIL_HOST_USER}" >> .env
      echo "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}" >> .env
      echo "EMAIL_USE_TLS=${EMAIL_USE_TLS}" >> .env
      echo "EMAIL_USE_SSL=${EMAIL_USE_SSL}" >> .env
  script:
    - docker-compose up --build -d --force-recreate
  variables:
    PROJECT_ID: $PROJECT_ID
    APP_PORT: $APP_PORT
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_DATADIR: $POSTGRES_DATADIR
    POSTGRES_PORT: $POSTGRES_PORT
    ALLOWED_HOSTS: $ALLOWED_HOSTS
    CSRF_TRUSTED_ORIGINS: $CSRF_TRUSTED_ORIGINS
    DEBUG: $DEBUG
    DJANGO_EMAIL_BACKEND: $DJANGO_EMAIL_BACKEND
    DJANGO_DEFAULT_FROM_EMAIL: $DJANGO_DEFAULT_FROM_EMAIL
    MAP_STYLE: $MAP_STYLE
    MAP_ASSETS_BASE_URL: $MAP_ASSETS_BASE_URL
    HERE_API_KEY: $HERE_API_KEY
    VIRTUAL_HOST: $VIRTUAL_HOST
    VIRTUAL_PORT: $VIRTUAL_PORT
    LETSENCRYPT_HOST: $LETSENCRYPT_HOST
    LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
    SECRET_KEY: $SECRET_KEY
    DJANGO_EMAIL_HOST: $DJANGO_EMAIL_HOST
    EMAIL_PORT: $EMAIL_PORT
    EMAIL_HOST_USER: $EMAIL_HOST_USER
    EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
    EMAIL_USE_TLS: $EMAIL_USE_TLS
    EMAIL_USE_SSL: $EMAIL_USE_SSL

deploy_application_dev:
  extends: .deploy_application
  tags:
    - pcc-dev
  environment: development
  variables:
    ENV: dev
  only:
    - development

deploy_application_hom:
  extends: .deploy_application
  tags:
    - PCC-HOM
  environment: staging
  variables:
    ENV: hom
  only:
    - release

deploy_application_prod:
  extends: .deploy_application
  tags:
    - PCC-PROD
  environment: production
  variables:
    ENV: prod
  only:
    - master

