stages:
  - deploy

deploy_application:
  tags:
    - PCC-HOM
  only:
    - release
  stage: deploy
  script:
    - docker-compose up --build -d --force-recreate
  variables:
    PROJECT_ID: $PROJECT_ID
    APP_PORT: $APP_PORT
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_DATADIR: $POSTGRES_DATADIR
    POSTGRES_PORT: $POSTGRES_PORT
    ALLOWED_HOSTS: $ALLOWED_HOSTS
    DEBUG: $DEBUG
    DJANGO_EMAIL_BACKEND: $DJANGO_EMAIL_BACKEND
    DJANGO_DEFAULT_FROM_EMAIL: $DJANGO_DEFAULT_FROM_EMAIL
    MAP_STYLE: $MAP_STYLE
    MAP_ASSETS_BASE_URL: $MAP_ASSETS_BASE_URL
    HERE_API_KEY: $HERE_API_KEY
    VIRTUAL_HOST: $VIRTUAL_HOST
    VIRTUAL_PORT: $VIRTUAL_PORT
    LETSENCRYPT_HOST: $LETSENCRYPT_HOST
    LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
    SECRET_KEY: $SECRET_KEY
    DJANGO_EMAIL_HOST: $DJANGO_EMAIL_HOST
    EMAIL_PORT: $EMAIL_PORT
    EMAIL_HOST_USER: $EMAIL_HOST_USER
    EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
    EMAIL_USE_TLS: $EMAIL_USE_TLS
    EMAIL_USE_SSL: $EMAIL_USE_SSL
