version: '2.4'

services:
  app:
    container_name: platform-coop-directory_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAP_ASSETS_BASE_URL=${MAP_ASSETS_BASE_URL}
        - MAP_STYLE=${MAP_STYLE}
        - SECRET_KEY=${SECRET_KEY}
    ports:
      - ${APP_PORT}:8000
    environment:
      - DATABASE_URL=postgis://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DJANGO_EMAIL_BACKEND=${DJANGO_EMAIL_BACKEND}
      - PROJECT_ID=${PROJECT_ID}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST}
      - DJANGO_DEFAULT_FROM_EMAIL=${DJANGO_DEFAULT_FROM_EMAIL}
      - DEBUG=${DEBUG:-false}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - SECRET_KEY=${SECRET_KEY}
      - HERE_API_KEY=${HERE_API_KEY}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - MAP_ASSETS_BASE_URL=${MAP_ASSETS_BASE_URL}
      - MAP_STYLE=${MAP_STYLE}
    networks:
      - default
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:12-3.0
    container_name: platform-coop-directory_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${POSTGRES_DB}"]
      timeout: 60s
      interval: 10s
      retries: 10
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    volumes:
      - ${POSTGRES_DATADIR}:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
