services:
  app:
    container_name: pcc-directory_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAP_ASSETS_BASE_URL=${MAP_ASSETS_BASE_URL}
        - MAP_STYLE=${MAP_STYLE}
        - SECRET_KEY=${SECRET_KEY}
    ports:
      - ${APP_PORT}:8000
    environment:
      - DATABASE_URL=postgis://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DJANGO_EMAIL_BACKEND=${DJANGO_EMAIL_BACKEND}
      - PROJECT_ID=${PROJECT_ID}
      - CACHE_TIMEOUT=${CACHE_TIMEOUT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST}
      - DJANGO_DEFAULT_FROM_EMAIL=${DJANGO_DEFAULT_FROM_EMAIL}
      - DEBUG=${DEBUG:-false}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - SECRET_KEY=${SECRET_KEY}
      - HERE_API_KEY=${HERE_API_KEY}
      - MAP_ASSETS_BASE_URL=${MAP_ASSETS_BASE_URL}
      - MAP_STYLE=${MAP_STYLE}
      - DJANGO_SETTINGS_MODULE=cmdi.settings
    restart: always
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:13-3.1
    container_name: pcc-directory_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${POSTGRES_DB}"]
      timeout: 60s
      interval: 10s
      retries: 10
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    volumes:
      - /etc/databases/directory:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis/redis-stack:latest
    container_name: pcc-directory_redis
    environment:
      - REDIS_PORT=${REDIS_PORT}
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - default
