# Generated by Django 3.0.7 on 2021-03-26 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdi', '0086_organizationadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAdminMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdi.Organization')),
            ],
            options={
                'verbose_name': 'Organization and Admins Relationships',
            },
        ),
        migrations.DeleteModel(
            name='OrganizationAdmin',
        ),
    ]
