# Generated by Django 3.0.7 on 2021-03-29 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0087_auto_20210326_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationadminmember',
            options={'ordering': ['-approved', '-created_at'], 'verbose_name': 'Organization and Admin Relationship', 'verbose_name_plural': 'Organizations and Admins Relationships'},
        ),
        migrations.AddField(
            model_name='organizationadminmember',
            name='left_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='organizationadminmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_admins_members', to='mdi.Organization'),
        ),
    ]
