# Generated by Django 3.0.7 on 2021-03-29 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdi', '0088_auto_20210329_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationadminmember',
            name='opinion_made_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinion_for_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
