# Generated by Django 3.0.7 on 2021-04-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdi', '0089_organizationadminmember_opinion_made_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
